#
# Makefile for plot widgets (Sun version)
#
CC = acc 
#CFLAGS=  -g
CFLAGS=  -O
#CFLAGS= -g -I/usr/products/openwin/v3_0/include
#CFLAGS= -I/usr/products/openwin/v3_0/include
LIBS = -L/usr/lib/X11 -lXm -lXt -lX11 -lm
#LIBS = -Bstatic -L/usr/products/motif/usr/lib -lXm -lXt -lX11 -lm
#AR=/usr/5bin/ar
AR=ar

include Makefile.common
