#
# Makefile for plot widgets (Linux version)
#
CC=cc
AR=ar
# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#CFLAGS = -g2 -DFUNCPROTO
CFLAGS= -g -I/usr/X11R6/include -DUSE_DIRENT -DUSE_LPR_PRINT_CMD
LIBS= -L/usr/X11R6/lib -lm -lXm -lXpm -lXext -lXt -lSM -lICE -lX11

include Makefile.common
